### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by world2025** [fongyk/MultiLayerGraph#1]
您好！请问有关于您这个开源的文章吗？目前也想了解一下基于图神经网络的图像检索，请问您还有类似的文章推荐吗？谢谢！

**Comment by fongyk** [comment]
抱歉，今天才看到你的issue。
图神经网络专门应用于检索任务的确实不多，NeurIPS 2019这篇检索的性能做得挺高：
```
Guided Similarity Separation for Image Retrieval, NeurIPS,  2019.
```
我看到大部分都是做半监督分类任务的，我这个repo是基于 GraphSAGE 在检索任务的一点探索。GraphSAGE：
```
Inductive Representation Learning on Large Graphs, NeurIPS, 2017.
```
另外有一些关于图神经网络的 [Tutorials](http://geometricdeeplearning.com/)，感兴趣的话可以看看。

**Comment by world2025** [comment]
耗得起，非常感谢



发自我的iPhone


------------------ Original ------------------

**Comment by world2025** [comment]
好的，非常感谢！



发自我的iPhone


------------------ Original ------------------
